DROP DATABASE IF EXISTS scheduler;
CREATE DATABASE scheduler;

USE scheduler;

CREATE TABLE events (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    start_date DATETIME NOT NULL,
	end_date DATETIME NOT NULL,
	text VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
    
);

